apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: xorstage
  description: Backstage instance for XOR organization
  annotations:
    github.com/project-slug: upendrasahu/xorstage
    backstage.io/techdocs-ref: dir:.
    backstage.io/view-url: https://github.com/upendrasahu/xorstage
    backstage.io/edit-url: https://github.com/upendrasahu/xorstage/edit/main
    backstage.io/source-location: url:https://github.com/upendrasahu/xorstage
  tags:
    - backstage
    - developer-portal
  links:
    - url: https://github.com/upendrasahu/xorstage
      title: GitHub Repository
      icon: github
spec:
  type: website
  lifecycle: production
  owner: group:upendrasahu
  system: developer-portal
  dependsOn:
    - resource:default/postgresql-db
